// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/20/2025, 6:04:41 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/plugins/**/*.{js,ts,mjs}","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/composables/**/*.{js,ts,mjs}","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/utils/**/*.{js,ts,mjs}","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/pages/about.vue","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/pages/index.vue","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/pages/tasktracker.vue","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/app.config.{js,ts,mjs}","/Users/chanonsangsomchaipipat/Desktop/devops_learning_app/nuxt_todos/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;